[2023-01-08 10:07:06,161] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2023-01-08T10:06:57.530111+00:00 [queued]>
[2023-01-08 10:07:06,166] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2023-01-08T10:06:57.530111+00:00 [queued]>
[2023-01-08 10:07:06,166] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 10:07:06,166] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-01-08 10:07:06,166] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 10:07:06,177] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): training_model> on 2023-01-08 10:06:57.530111+00:00
[2023-01-08 10:07:06,185] {standard_task_runner.py:52} INFO - Started process 11799 to run task
[2023-01-08 10:07:06,193] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'training_model', 'manual__2023-01-08T10:06:57.530111+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmp6f9k4mh1', '--error-file', '/tmp/tmpsnuxmljv']
[2023-01-08 10:07:06,193] {standard_task_runner.py:80} INFO - Job 86: Subtask training_model
[2023-01-08 10:07:06,236] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2023-01-08T10:06:57.530111+00:00 [running]> on host 1f037b111ba5
[2023-01-08 10:07:06,292] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=training_model
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T10:06:57.530111+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T10:06:57.530111+00:00
[2023-01-08 10:07:06,293] {logging_mixin.py:115} INFO - DBPath/home/airflow/dags/Lead_scoring_data_pipeline/Lead_scoring_mlflow_production.db
[2023-01-08 10:07:06,294] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 182, in get_trained_model
    build_dbs_MLFlow()
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 65, in build_dbs_MLFlow
    if os.path.isfile(DB_PATH+DB_FILE_MLFLOW):
NameError: name 'os' is not defined
[2023-01-08 10:07:06,298] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_scoring_training_pipeline, task_id=training_model, execution_date=20230108T100657, start_date=20230108T100706, end_date=20230108T100706
[2023-01-08 10:07:06,309] {standard_task_runner.py:92} ERROR - Failed to execute job 86 for task training_model (name 'os' is not defined; 11799)
[2023-01-08 10:07:06,319] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-08 10:07:06,341] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
