[2023-01-08 09:13:20,312] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.mapping_categorical_vars_test manual__2023-01-08T09:13:05.218977+00:00 [queued]>
[2023-01-08 09:13:20,317] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.mapping_categorical_vars_test manual__2023-01-08T09:13:05.218977+00:00 [queued]>
[2023-01-08 09:13:20,317] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 09:13:20,317] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-01-08 09:13:20,317] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 09:13:20,329] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): mapping_categorical_vars_test> on 2023-01-08 09:13:05.218977+00:00
[2023-01-08 09:13:20,334] {standard_task_runner.py:52} INFO - Started process 6356 to run task
[2023-01-08 09:13:20,340] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline_test', 'mapping_categorical_vars_test', 'manual__2023-01-08T09:13:05.218977+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/unit_test/.ipynb_checkpoints/lead_scoring_data_pipeline_test-checkpoint.py', '--cfg-path', '/tmp/tmpcra1vrk8', '--error-file', '/tmp/tmprkmhkaru']
[2023-01-08 09:13:20,342] {standard_task_runner.py:80} INFO - Job 65: Subtask mapping_categorical_vars_test
[2023-01-08 09:13:20,389] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.mapping_categorical_vars_test manual__2023-01-08T09:13:05.218977+00:00 [running]> on host 1f037b111ba5
[2023-01-08 09:13:20,435] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline_test
AIRFLOW_CTX_TASK_ID=mapping_categorical_vars_test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T09:13:05.218977+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T09:13:05.218977+00:00
[2023-01-08 09:13:20,452] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:200 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:13:20,455] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:209 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:13:20,459] {logging_mixin.py:115} WARNING - /home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py:218 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2023-01-08 09:13:20,493] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/test_with_pytest.py", line 83, in test_map_categorical_vars
    assert df.equals(df_test)
AssertionError
[2023-01-08 09:13:20,496] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_Scoring_Data_Engineering_Pipeline_test, task_id=mapping_categorical_vars_test, execution_date=20230108T091305, start_date=20230108T091320, end_date=20230108T091320
[2023-01-08 09:13:20,504] {standard_task_runner.py:92} ERROR - Failed to execute job 65 for task mapping_categorical_vars_test (; 6356)
[2023-01-08 09:13:20,548] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-08 09:13:20,568] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
