[2023-01-07 18:17:47,250] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-07T18:17:43.204364+00:00 [queued]>
[2023-01-07 18:17:47,255] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-07T18:17:43.204364+00:00 [queued]>
[2023-01-07 18:17:47,255] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-07 18:17:47,255] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-01-07 18:17:47,255] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-07 18:17:47,266] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): building_db_test> on 2023-01-07 18:17:43.204364+00:00
[2023-01-07 18:17:47,269] {standard_task_runner.py:52} INFO - Started process 4982 to run task
[2023-01-07 18:17:47,274] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline_test', 'building_db_test', 'manual__2023-01-07T18:17:43.204364+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/unit_test/lead_scoring_data_pipeline_test.py', '--cfg-path', '/tmp/tmppvk4uzzo', '--error-file', '/tmp/tmpepy888ld']
[2023-01-07 18:17:47,276] {standard_task_runner.py:80} INFO - Job 17: Subtask building_db_test
[2023-01-07 18:17:47,320] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-07T18:17:43.204364+00:00 [running]> on host 53a4c6599d84
[2023-01-07 18:17:47,357] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline_test
AIRFLOW_CTX_TASK_ID=building_db_test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-07T18:17:43.204364+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-07T18:17:43.204364+00:00
[2023-01-07 18:17:47,358] {logging_mixin.py:115} INFO - DBPath/home/airflow/dags/Lead_scoring_data_pipeline/unit_testlead_scoring_data_cleaning.db
[2023-01-07 18:17:47,358] {logging_mixin.py:115} INFO - DB Already Exsist
[2023-01-07 18:17:47,359] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/test_with_pytest.py", line 26, in test_load_data_into_db
    load_data_into_db()
  File "/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/utils.py", line 104, in load_data_into_db
    df_lead_scoring = pd.read_csv(DATA_DIRECTORY+'leadscoring_test.csv')
  File "/opt/conda/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 680, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 575, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 934, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1218, in _make_engine
    self.handles = get_handle(  # type: ignore[call-overload]
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/common.py", line 786, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_data_pipeline/data/leadscoring_test.csv'
[2023-01-07 18:17:47,363] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_Scoring_Data_Engineering_Pipeline_test, task_id=building_db_test, execution_date=20230107T181743, start_date=20230107T181747, end_date=20230107T181747
[2023-01-07 18:17:47,372] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task building_db_test ([Errno 2] No such file or directory: '/home/airflow/dags/Lead_scoring_data_pipeline/data/leadscoring_test.csv'; 4982)
[2023-01-07 18:17:47,403] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-07 18:17:47,427] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
