[2023-01-08 11:38:30,074] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2023-01-08T11:38:06.463183+00:00 [queued]>
[2023-01-08 11:38:30,079] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2023-01-08T11:38:06.463183+00:00 [queued]>
[2023-01-08 11:38:30,079] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 11:38:30,079] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-01-08 11:38:30,079] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 11:38:30,091] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): training_model> on 2023-01-08 11:38:06.463183+00:00
[2023-01-08 11:38:30,097] {standard_task_runner.py:52} INFO - Started process 24555 to run task
[2023-01-08 11:38:30,104] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_scoring_training_pipeline', 'training_model', 'manual__2023-01-08T11:38:06.463183+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_training_pipeline/.ipynb_checkpoints/lead_scoring_training_pipeline-checkpoint.py', '--cfg-path', '/tmp/tmpb4z1dnjk', '--error-file', '/tmp/tmpm4ixf5ng']
[2023-01-08 11:38:30,105] {standard_task_runner.py:80} INFO - Job 142: Subtask training_model
[2023-01-08 11:38:30,150] {task_command.py:371} INFO - Running <TaskInstance: Lead_scoring_training_pipeline.training_model manual__2023-01-08T11:38:06.463183+00:00 [running]> on host 1f037b111ba5
[2023-01-08 11:38:30,199] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_scoring_training_pipeline
AIRFLOW_CTX_TASK_ID=training_model
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T11:38:06.463183+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T11:38:06.463183+00:00
[2023-01-08 11:38:30,764] {logging_mixin.py:115} WARNING - /opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py:72 DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
[2023-01-08 11:38:34,535] {logging_mixin.py:115} WARNING - Registered model 'LightGBM' already exists. Creating a new version of this model...
[2023-01-08 11:38:34,567] {logging_mixin.py:115} WARNING - 2023/01/08 11:38:34 INFO mlflow.tracking._model_registry.client: Waiting up to 300 seconds for model version to finish creation.                     Model name: LightGBM, version 4
[2023-01-08 11:38:34,568] {logging_mixin.py:115} WARNING - Created version '4' of model 'LightGBM'.
[2023-01-08 11:38:34,620] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_training_pipeline/utils.py", line 212, in get_trained_model
    auc = roc_auc_score(y_pred, y_test)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 390, in roc_auc_score
    return _average_binary_score(partial(_binary_roc_auc_score,
  File "/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_base.py", line 77, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/opt/conda/lib/python3.8/site-packages/sklearn/metrics/_ranking.py", line 223, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
[2023-01-08 11:38:34,628] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_scoring_training_pipeline, task_id=training_model, execution_date=20230108T113806, start_date=20230108T113830, end_date=20230108T113834
[2023-01-08 11:38:34,638] {standard_task_runner.py:92} ERROR - Failed to execute job 142 for task training_model (Only one class present in y_true. ROC AUC score is not defined in that case.; 24555)
[2023-01-08 11:38:34,685] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-08 11:38:34,713] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
