[2023-01-08 08:55:25,557] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T08:55:22.491468+00:00 [queued]>
[2023-01-08 08:55:25,562] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T08:55:22.491468+00:00 [queued]>
[2023-01-08 08:55:25,562] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 08:55:25,562] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-01-08 08:55:25,562] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 08:55:25,574] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): building_db_test> on 2023-01-08 08:55:22.491468+00:00
[2023-01-08 08:55:25,578] {standard_task_runner.py:52} INFO - Started process 4104 to run task
[2023-01-08 08:55:25,584] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline_test', 'building_db_test', 'manual__2023-01-08T08:55:22.491468+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/unit_test/.ipynb_checkpoints/lead_scoring_data_pipeline_test-checkpoint.py', '--cfg-path', '/tmp/tmpth69_7rc', '--error-file', '/tmp/tmp8u4efd01']
[2023-01-08 08:55:25,585] {standard_task_runner.py:80} INFO - Job 45: Subtask building_db_test
[2023-01-08 08:55:25,631] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T08:55:22.491468+00:00 [running]> on host 1f037b111ba5
[2023-01-08 08:55:25,679] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline_test
AIRFLOW_CTX_TASK_ID=building_db_test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T08:55:22.491468+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T08:55:22.491468+00:00
[2023-01-08 08:55:26,044] {logging_mixin.py:115} INFO - df.shape[0] :24991
[2023-01-08 08:55:26,044] {logging_mixin.py:115} INFO - df_test.shape[0] :100
[2023-01-08 08:55:26,044] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/test_with_pytest.py", line 30, in test_load_data_into_db
    assert df.shape[0] == df_test.shape[0]
AssertionError
[2023-01-08 08:55:26,047] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=Lead_Scoring_Data_Engineering_Pipeline_test, task_id=building_db_test, execution_date=20230108T085522, start_date=20230108T085525, end_date=20230108T085526
[2023-01-08 08:55:26,061] {standard_task_runner.py:92} ERROR - Failed to execute job 45 for task building_db_test (; 4104)
[2023-01-08 08:55:26,074] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-08 08:55:26,100] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
