[2023-01-08 08:48:21,645] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T08:48:11.833530+00:00 [queued]>
[2023-01-08 08:48:21,650] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T08:48:11.833530+00:00 [queued]>
[2023-01-08 08:48:21,650] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 08:48:21,650] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-01-08 08:48:21,651] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-01-08 08:48:21,663] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): building_db_test> on 2023-01-08 08:48:11.833530+00:00
[2023-01-08 08:48:21,667] {standard_task_runner.py:52} INFO - Started process 3231 to run task
[2023-01-08 08:48:21,674] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'Lead_Scoring_Data_Engineering_Pipeline_test', 'building_db_test', 'manual__2023-01-08T08:48:11.833530+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/Lead_scoring_data_pipeline/unit_test/.ipynb_checkpoints/lead_scoring_data_pipeline_test-checkpoint.py', '--cfg-path', '/tmp/tmpksultki5', '--error-file', '/tmp/tmpq0hhupy4']
[2023-01-08 08:48:21,675] {standard_task_runner.py:80} INFO - Job 40: Subtask building_db_test
[2023-01-08 08:48:21,720] {task_command.py:371} INFO - Running <TaskInstance: Lead_Scoring_Data_Engineering_Pipeline_test.building_db_test manual__2023-01-08T08:48:11.833530+00:00 [running]> on host 1f037b111ba5
[2023-01-08 08:48:21,765] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=Lead_Scoring_Data_Engineering_Pipeline_test
AIRFLOW_CTX_TASK_ID=building_db_test
AIRFLOW_CTX_EXECUTION_DATE=2023-01-08T08:48:11.833530+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-01-08T08:48:11.833530+00:00
[2023-01-08 08:48:21,766] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 2020, in execute
    cur.execute(*args, **kwargs)
sqlite3.OperationalError: no such table: loaded_data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/opt/conda/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/airflow/dags/Lead_scoring_data_pipeline/unit_test/test_with_pytest.py", line 26, in test_load_data_into_db
    df_score = pd.read_sql('select * from loaded_data', conn)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 566, in read_sql
    return pandas_sql.read_query(
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 2080, in read_query
    cursor = self.execute(*args)
  File "/opt/conda/lib/python3.8/site-packages/pandas/io/sql.py", line 2032, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select * from loaded_data': no such table: loaded_data
[2023-01-08 08:48:21,770] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=Lead_Scoring_Data_Engineering_Pipeline_test, task_id=building_db_test, execution_date=20230108T084811, start_date=20230108T084821, end_date=20230108T084821
[2023-01-08 08:48:21,778] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task building_db_test (Execution failed on sql 'select * from loaded_data': no such table: loaded_data; 3231)
[2023-01-08 08:48:21,801] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-01-08 08:48:21,832] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
